In [1]:
%pip install pandas pyarrow requests tqdm python-dateutil

Requirement already satisfied: pandas in d:\anaconda3\Lib\site-packages (3.0.3)
Requirement already satisfied: pyarrow in d:\anaconda3\Lib\site-packages (23.0.1)
Requirement already satisfied: requests in d:\anaconda3\Lib\site-packages (2.34.2)
Requirement already satisfied: tqdm in d:\anaconda3\Lib\site-packages (4.68.2)
Requirement already satisfied: python-dateutil in C:\Users\felip\AppData\Roaming\Python\Python314\site-packages (2.9.0.post0)
Requirement already satisfied: numpy>=2.3.3 in d:\anaconda3\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: tzdata in d:\anaconda3\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: charset_normalizer<4,>=2 in d:\anaconda3\Lib\site-packages (from requests) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in d:\anaconda3\Lib\site-packages (from requests) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in d:\anaconda3\Lib\site-packages (from requests) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in d:\anaconda3\Lib\site-packages (from requests) (2026.6.17)
Requirement already satisfied: colorama in C:\Users\felip\AppData\Roaming\Python\Python314\site-packages (from tqdm) (0.4.6)
Requirement already satisfied: six>=1.5 in C:\Users\felip\AppData\Roaming\Python\Python314\site-packages (from python-dateutil) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd 
import requests 
from pathlib  import Path 
from datetime import datetime 
import zipfile
import io
from concurrent.futures import ThreadPoolExecutor, as_completed

In [2]:
diretorio_base = Path(r"E:\2. budget_educacao")
diretorio_download = diretorio_base / "dados_despesas_diarias"
diretorio_download.mkdir(exist_ok=True)

In [ ]:
datas = pd.date_range(start="2021-03-04", end="2021-12-31", freq="D")

import time

link_base = [
    f"https://dadosabertos-download.cgu.gov.br/PortalDaTransparencia/saida/despesas/{d.strftime('%Y%m%d')}_Despesas.zip"
    for d in datas
]

headers = {"User-Agent": "Mozilla/5.0"}
pausa_entre_arquivos = 5        # segundos entre um download e outro
pausa_bloqueio = 5 * 60        # 15 minutos quando o servidor bloquear
max_tentativas = 2

for url in link_base:
    arquivo = diretorio_download / url.split("/")[-1]
    if arquivo.exists():
        print(f"ja tem: {arquivo.name}")
        continue

    baixou = False
    for tentativa in range(1, max_tentativas + 1):
        try:
            print(f"baixando: {arquivo.name} (tentativa {tentativa})")
            r = requests.get(url, headers=headers, timeout=60)
        except Exception as e:
            print(f"Erro: {e}")
            time.sleep(60)
            continue

        if r.status_code == 200:
            with open(arquivo, "wb") as f:
                f.write(r.content)
            baixou = True
            break
        elif r.status_code in (403, 405, 429):
            print(f"bloqueado (HTTP {r.status_code}). esperando {pausa_bloqueio // 60} min...")
            time.sleep(pausa_bloqueio)
        else:
            print(f"erro no http {r.status_code} pulando arquivo")
            break

    if not baixou and r.status_code in (403, 405, 429):
        print("continua bloqueando, parando o script")
        break

    time.sleep(pausa_entre_arquivos)

ja tem: 20210304_Despesas.zip
ja tem: 20210305_Despesas.zip
ja tem: 20210306_Despesas.zip
ja tem: 20210307_Despesas.zip
ja tem: 20210308_Despesas.zip
ja tem: 20210309_Despesas.zip
ja tem: 20210310_Despesas.zip
ja tem: 20210311_Despesas.zip
ja tem: 20210312_Despesas.zip
ja tem: 20210313_Despesas.zip
ja tem: 20210314_Despesas.zip
ja tem: 20210315_Despesas.zip
ja tem: 20210316_Despesas.zip
ja tem: 20210317_Despesas.zip
ja tem: 20210318_Despesas.zip
ja tem: 20210319_Despesas.zip
ja tem: 20210320_Despesas.zip
ja tem: 20210321_Despesas.zip
ja tem: 20210322_Despesas.zip
ja tem: 20210323_Despesas.zip
ja tem: 20210324_Despesas.zip
ja tem: 20210325_Despesas.zip
ja tem: 20210326_Despesas.zip
ja tem: 20210327_Despesas.zip
ja tem: 20210328_Despesas.zip
ja tem: 20210329_Despesas.zip
ja tem: 20210330_Despesas.zip
ja tem: 20210331_Despesas.zip
ja tem: 20210401_Despesas.zip
ja tem: 20210402_Despesas.zip
ja tem: 20210403_Despesas.zip
ja tem: 20210404_Despesas.zip
ja tem: 20210405_Despesas.zip
ja tem: 20210406_Despesas.zip
ja tem: 20210407_Despesas.zip
ja tem: 20210408_Despesas.zip
ja tem: 20210409_Despesas.zip
ja tem: 20210410_Despesas.zip
ja tem: 20210411_Despesas.zip
ja tem: 20210412_Despesas.zip
ja tem: 20210413_Despesas.zip
ja tem: 20210414_Despesas.zip
ja tem: 20210415_Despesas.zip
ja tem: 20210416_Despesas.zip
ja tem: 20210417_Despesas.zip
ja tem: 20210418_Despesas.zip
ja tem: 20210419_Despesas.zip
ja tem: 20210420_Despesas.zip
ja tem: 20210421_Despesas.zip
ja tem: 20210422_Despesas.zip
ja tem: 20210423_Despesas.zip
ja tem: 20210424_Despesas.zip
ja tem: 20210425_Despesas.zip
ja tem: 20210426_Despesas.zip
ja tem: 20210427_Despesas.zip
ja tem: 20210428_Despesas.zip
ja tem: 20210429_Despesas.zip
ja tem: 20210430_Despesas.zip
ja tem: 20210501_Despesas.zip
ja tem: 20210502_Despesas.zip
ja tem: 20210503_Despesas.zip
ja tem: 20210504_Despesas.zip
ja tem: 20210505_Despesas.zip
ja tem: 20210506_Despesas.zip
ja tem: 20210507_Despesas.zip
ja tem: 20210508_Despesas.zip
ja tem: 20210509_Despesas.zip
ja tem: 20210510_Despesas.zip
ja tem: 20210511_Despesas.zip
ja tem: 20210512_Despesas.zip
ja tem: 20210513_Despesas.zip
ja tem: 20210514_Despesas.zip
ja tem: 20210515_Despesas.zip
ja tem: 20210516_Despesas.zip
ja tem: 20210517_Despesas.zip
ja tem: 20210518_Despesas.zip
ja tem: 20210519_Despesas.zip
ja tem: 20210520_Despesas.zip
ja tem: 20210521_Despesas.zip
ja tem: 20210522_Despesas.zip
ja tem: 20210523_Despesas.zip
ja tem: 20210524_Despesas.zip
ja tem: 20210525_Despesas.zip
ja tem: 20210526_Despesas.zip
ja tem: 20210527_Despesas.zip
ja tem: 20210528_Despesas.zip
ja tem: 20210529_Despesas.zip
ja tem: 20210530_Despesas.zip
ja tem: 20210531_Despesas.zip
ja tem: 20210601_Despesas.zip
ja tem: 20210602_Despesas.zip
ja tem: 20210603_Despesas.zip
ja tem: 20210604_Despesas.zip
ja tem: 20210605_Despesas.zip
ja tem: 20210606_Despesas.zip
ja tem: 20210607_Despesas.zip
ja tem: 20210608_Despesas.zip
ja tem: 20210609_Despesas.zip
ja tem: 20210610_Despesas.zip
ja tem: 20210611_Despesas.zip
ja tem: 20210612_Despesas.zip
ja tem: 20210613_Despesas.zip
ja tem: 20210614_Despesas.zip
ja tem: 20210615_Despesas.zip
ja tem: 20210616_Despesas.zip
ja tem: 20210617_Despesas.zip
ja tem: 20210618_Despesas.zip
ja tem: 20210619_Despesas.zip
ja tem: 20210620_Despesas.zip
ja tem: 20210621_Despesas.zip
ja tem: 20210622_Despesas.zip
ja tem: 20210623_Despesas.zip
ja tem: 20210624_Despesas.zip
ja tem: 20210625_Despesas.zip
ja tem: 20210626_Despesas.zip
baixando: 20210627_Despesas.zip (tentativa 1)
bloqueado (HTTP 403). esperando 5 min...
baixando: 20210627_Despesas.zip (tentativa 2)
bloqueado (HTTP 403). esperando 5 min...

In [ ]:
datas = pd.date_range(start="2021-03-04", end="2021-12-31", freq="D")

link_base = [
    f"https://dadosabertos-download.cgu.gov.br/PortalDaTransparencia/saida/despesas/{d.strftime('%Y%m%d')}_Despesas.zip"
    for d in datas
]

for url in link_base:
    arquivo = diretorio_download / url.split("/")[-1]
    if arquivo.exists():
        print(f"Já existe: {arquivo.name}")
        continue
    try:
        print(f"Baixando: {arquivo.name}")
        r = requests.get(url, timeout=60)
        if r.status_code == 200:
            with open(arquivo, "wb") as f:
                f.write(r.content)
        else:
            print(f"Erro HTTP {r.status_code}")
    except Exception as e:
        print(f"Erro: {e}")

Baixando: 20210304_Despesas.zip
Baixando: 20210305_Despesas.zip
Baixando: 20210306_Despesas.zip
Já existe: 20210307_Despesas.zip
Baixando: 20210308_Despesas.zip
Baixando: 20210309_Despesas.zip
Baixando: 20210310_Despesas.zip
Baixando: 20210311_Despesas.zip
Baixando: 20210312_Despesas.zip
Baixando: 20210313_Despesas.zip
Baixando: 20210314_Despesas.zip
Baixando: 20210315_Despesas.zip
Baixando: 20210316_Despesas.zip
Baixando: 20210317_Despesas.zip
Baixando: 20210318_Despesas.zip
Baixando: 20210319_Despesas.zip
Baixando: 20210320_Despesas.zip
Baixando: 20210321_Despesas.zip
Baixando: 20210322_Despesas.zip
Baixando: 20210323_Despesas.zip
Baixando: 20210324_Despesas.zip
Baixando: 20210325_Despesas.zip
Baixando: 20210326_Despesas.zip
Baixando: 20210327_Despesas.zip
Baixando: 20210328_Despesas.zip
Baixando: 20210329_Despesas.zip
Baixando: 20210330_Despesas.zip
Baixando: 20210331_Despesas.zip
Baixando: 20210401_Despesas.zip
Baixando: 20210402_Despesas.zip
Baixando: 20210403_Despesas.zip
Baixando: 20210404_Despesas.zip
Baixando: 20210405_Despesas.zip
Baixando: 20210406_Despesas.zip
Baixando: 20210407_Despesas.zip
Erro HTTP 405
Baixando: 20210408_Despesas.zip
Erro HTTP 405
Baixando: 20210409_Despesas.zip
Erro HTTP 405
Baixando: 20210410_Despesas.zip
Erro HTTP 405
Baixando: 20210411_Despesas.zip
Erro HTTP 405
Baixando: 20210412_Despesas.zip
Erro HTTP 405
Baixando: 20210413_Despesas.zip
Erro HTTP 405
Baixando: 20210414_Despesas.zip
Erro HTTP 405
Baixando: 20210415_Despesas.zip
Erro HTTP 405
Baixando: 20210416_Despesas.zip
Erro HTTP 405
Baixando: 20210417_Despesas.zip
Erro HTTP 405
Baixando: 20210418_Despesas.zip
Erro HTTP 405
Baixando: 20210419_Despesas.zip
Erro HTTP 405
Baixando: 20210420_Despesas.zip
Erro HTTP 405
Baixando: 20210421_Despesas.zip
Erro HTTP 405
Baixando: 20210422_Despesas.zip
Erro HTTP 405
Baixando: 20210423_Despesas.zip
Erro HTTP 405
Baixando: 20210424_Despesas.zip
Erro HTTP 405
Baixando: 20210425_Despesas.zip
Erro HTTP 405
Baixando: 20210426_Despesas.zip
Erro HTTP 405
Baixando: 20210427_Despesas.zip
Erro HTTP 405
Baixando: 20210428_Despesas.zip
Erro HTTP 405
Baixando: 20210429_Despesas.zip
Erro HTTP 405
Baixando: 20210430_Despesas.zip
Erro HTTP 405
Baixando: 20210501_Despesas.zip
Erro HTTP 405
Baixando: 20210502_Despesas.zip
Erro HTTP 405
Baixando: 20210503_Despesas.zip
Erro HTTP 405
Baixando: 20210504_Despesas.zip
Erro HTTP 405
Baixando: 20210505_Despesas.zip
Erro HTTP 405
Baixando: 20210506_Despesas.zip
Erro HTTP 405
Baixando: 20210507_Despesas.zip
Erro HTTP 405
Baixando: 20210508_Despesas.zip
Erro HTTP 405
Baixando: 20210509_Despesas.zip
Erro HTTP 405
Baixando: 20210510_Despesas.zip
Erro HTTP 405
Baixando: 20210511_Despesas.zip
Erro HTTP 405
Baixando: 20210512_Despesas.zip
Erro HTTP 405
Baixando: 20210513_Despesas.zip
Erro HTTP 405
Baixando: 20210514_Despesas.zip
Erro HTTP 405
Baixando: 20210515_Despesas.zip
Erro HTTP 405
Baixando: 20210516_Despesas.zip
Erro HTTP 405
Baixando: 20210517_Despesas.zip
Erro HTTP 405
Baixando: 20210518_Despesas.zip
Erro HTTP 405
Baixando: 20210519_Despesas.zip
Erro HTTP 405
Baixando: 20210520_Despesas.zip
Erro HTTP 405
Baixando: 20210521_Despesas.zip
Erro HTTP 405
Baixando: 20210522_Despesas.zip
Erro HTTP 405
Baixando: 20210523_Despesas.zip
Erro HTTP 405
Baixando: 20210524_Despesas.zip
Erro HTTP 405
Baixando: 20210525_Despesas.zip
Erro HTTP 405
Baixando: 20210526_Despesas.zip
Erro HTTP 405
Baixando: 20210527_Despesas.zip
Erro HTTP 405
Baixando: 20210528_Despesas.zip
Erro HTTP 405
Baixando: 20210529_Despesas.zip
Erro HTTP 405
Baixando: 20210530_Despesas.zip
Erro HTTP 405
Baixando: 20210531_Despesas.zip
Erro HTTP 405
Baixando: 20210601_Despesas.zip
Erro HTTP 405
Baixando: 20210602_Despesas.zip
Erro HTTP 405
Baixando: 20210603_Despesas.zip
Erro HTTP 405
Baixando: 20210604_Despesas.zip
Erro HTTP 405
Baixando: 20210605_Despesas.zip
Erro HTTP 405
Baixando: 20210606_Despesas.zip
Erro HTTP 405
Baixando: 20210607_Despesas.zip
Erro HTTP 405
Baixando: 20210608_Despesas.zip
Erro HTTP 405
Baixando: 20210609_Despesas.zip
Erro HTTP 405
Baixando: 20210610_Despesas.zip
Erro HTTP 405
Baixando: 20210611_Despesas.zip
Erro HTTP 405
Baixando: 20210612_Despesas.zip
Erro HTTP 405
Baixando: 20210613_Despesas.zip
Erro HTTP 405
Baixando: 20210614_Despesas.zip
Erro HTTP 405
Baixando: 20210615_Despesas.zip
Erro HTTP 405
Baixando: 20210616_Despesas.zip
Erro HTTP 405
Baixando: 20210617_Despesas.zip
Erro HTTP 405
Baixando: 20210618_Despesas.zip
Erro HTTP 405
Baixando: 20210619_Despesas.zip
Erro HTTP 405
Baixando: 20210620_Despesas.zip
Erro HTTP 405
Baixando: 20210621_Despesas.zip
Erro HTTP 405
Baixando: 20210622_Despesas.zip
Erro HTTP 405
Baixando: 20210623_Despesas.zip
Erro HTTP 405
Baixando: 20210624_Despesas.zip
Erro HTTP 405
Baixando: 20210625_Despesas.zip
Erro HTTP 405
Baixando: 20210626_Despesas.zip
Erro HTTP 405
Baixando: 20210627_Despesas.zip
Erro HTTP 405
Baixando: 20210628_Despesas.zip
Erro HTTP 405
Baixando: 20210629_Despesas.zip
Erro HTTP 405
Baixando: 20210630_Despesas.zip
Erro HTTP 405
Baixando: 20210701_Despesas.zip
Erro HTTP 405
Baixando: 20210702_Despesas.zip
Erro HTTP 405
Baixando: 20210703_Despesas.zip
Erro HTTP 405
Baixando: 20210704_Despesas.zip
Erro HTTP 405
Baixando: 20210705_Despesas.zip

KeyboardInterrupt:

In [16]:
def processar_zip(zip_path: Path, pasta_parquet: Path) -> str:
    try:
        with zipfile.ZipFile(zip_path, "r") as z:
            csvs = [n for n in z.namelist() if n.endswith("_Empenho.csv")]
            for nome_csv in csvs:
                with z.open(nome_csv) as f:
                    df = pd.read_csv(
                        io.TextIOWrapper(f, encoding="latin1"),
                        sep=";",
                        low_memory=False,
                    )
                parquet_name = Path(nome_csv).stem + ".parquet"
                df.to_parquet(pasta_parquet / parquet_name, engine="pyarrow", index=False)
        return f"✓ {zip_path.name}"
    except Exception as e:
        return f"✗ {zip_path.name}: {e}"

pasta_parquet = diretorio_download / "dados_despesas_diarias_parquet"
pasta_parquet.mkdir(parents=True, exist_ok=True)

zips = list(diretorio_download.glob("*.zip"))
print(f"{len(zips)} arquivos encontrados.\n")

with ThreadPoolExecutor(max_workers=4) as executor:
    futuros = {executor.submit(processar_zip, z, pasta_parquet): z for z in zips}
    for i, futuro in enumerate(as_completed(futuros), 1):
        print(f"[{i}/{len(zips)}] {futuro.result()}")

730 arquivos encontrados.

[1/730] ✓ 20230101_Despesas.zip
[2/730] ✓ 20230102_Despesas.zip
[3/730] ✓ 20230103_Despesas.zip
[4/730] ✓ 20230104_Despesas.zip
[5/730] ✓ 20230107_Despesas.zip
[6/730] ✓ 20230105_Despesas.zip
[7/730] ✓ 20230108_Despesas.zip
[8/730] ✓ 20230106_Despesas.zip
[9/730] ✓ 20230109_Despesas.zip
[10/730] ✓ 20230110_Despesas.zip
[11/730] ✓ 20230111_Despesas.zip
[12/730] ✓ 20230114_Despesas.zip
[13/730] ✓ 20230112_Despesas.zip
[14/730] ✓ 20230115_Despesas.zip
[15/730] ✓ 20230113_Despesas.zip
[16/730] ✓ 20230117_Despesas.zip
[17/730] ✓ 20230118_Despesas.zip
[18/730] ✓ 20230116_Despesas.zip
[19/730] ✓ 20230122_Despesas.zip
[20/730] ✓ 20230121_Despesas.zip
[21/730] ✓ 20230119_Despesas.zip
[22/730] ✓ 20230120_Despesas.zip
[23/730] ✓ 20230123_Despesas.zip
[24/730] ✓ 20230125_Despesas.zip
[25/730] ✓ 20230124_Despesas.zip
[26/730] ✓ 20230128_Despesas.zip
[27/730] ✓ 20230129_Despesas.zip
[28/730] ✓ 20230126_Despesas.zip
[29/730] ✓ 20230127_Despesas.zip
[30/730] ✓ 20230130_Despesas.zip
[31/730] ✓ 20230131_Despesas.zip
[32/730] ✓ 20230201_Despesas.zip
[33/730] ✓ 20230204_Despesas.zip
[34/730] ✓ 20230205_Despesas.zip
[35/730] ✓ 20230202_Despesas.zip
[36/730] ✓ 20230203_Despesas.zip
[37/730] ✓ 20230206_Despesas.zip
[38/730] ✓ 20230207_Despesas.zip
[39/730] ✓ 20230208_Despesas.zip
[40/730] ✓ 20230211_Despesas.zip
[41/730] ✓ 20230212_Despesas.zip
[42/730] ✓ 20230209_Despesas.zip
[43/730] ✓ 20230210_Despesas.zip
[44/730] ✓ 20230213_Despesas.zip
[45/730] ✓ 20230215_Despesas.zip
[46/730] ✓ 20230218_Despesas.zip
[47/730] ✓ 20230220_Despesas.zip
[48/730] ✓ 20230216_Despesas.zip
[49/730] ✓ 20230214_Despesas.zip
[50/730] ✓ 20230221_Despesas.zip
[51/730] ✓ 20230217_Despesas.zip
[52/730] ✓ 20230225_Despesas.zip
[53/730] ✓ 20230222_Despesas.zip
[54/730] ✓ 20230226_Despesas.zip
[55/730] ✓ 20230223_Despesas.zip
[56/730] ✓ 20230224_Despesas.zip
[57/730] ✓ 20230227_Despesas.zip
[58/730] ✓ 20230301_Despesas.zip
[59/730] ✓ 20230304_Despesas.zip
[60/730] ✓ 20230302_Despesas.zip
[61/730] ✓ 20230305_Despesas.zip
[62/730] ✓ 20230228_Despesas.zip
[63/730] ✓ 20230303_Despesas.zip
[64/730] ✓ 20230306_Despesas.zip
[65/730] ✓ 20230307_Despesas.zip
[66/730] ✓ 20230308_Despesas.zip
[67/730] ✓ 20230311_Despesas.zip
[68/730] ✓ 20230312_Despesas.zip
[69/730] ✓ 20230309_Despesas.zip
[70/730] ✓ 20230310_Despesas.zip
[71/730] ✓ 20230315_Despesas.zip
[72/730] ✓ 20230313_Despesas.zip
[73/730] ✓ 20230314_Despesas.zip
[74/730] ✓ 20230318_Despesas.zip
[75/730] ✓ 20230319_Despesas.zip
[76/730] ✓ 20230316_Despesas.zip
[77/730] ✓ 20230317_Despesas.zip
[78/730] ✓ 20230320_Despesas.zip
[79/730] ✓ 20230322_Despesas.zip
[80/730] ✓ 20230321_Despesas.zip
[81/730] ✓ 20230325_Despesas.zip
[82/730] ✓ 20230324_Despesas.zip
[83/730] ✓ 20230326_Despesas.zip
[84/730] ✓ 20230323_Despesas.zip
[85/730] ✓ 20230327_Despesas.zip
[86/730] ✓ 20230328_Despesas.zip
[87/730] ✓ 20230401_Despesas.zip
[88/730] ✓ 20230329_Despesas.zip
[89/730] ✓ 20230402_Despesas.zip
[90/730] ✓ 20230330_Despesas.zip
[91/730] ✓ 20230331_Despesas.zip
[92/730] ✓ 20230403_Despesas.zip
[93/730] ✓ 20230404_Despesas.zip
[94/730] ✓ 20230405_Despesas.zip
[95/730] ✓ 20230407_Despesas.zip
[96/730] ✓ 20230409_Despesas.zip
[97/730] ✓ 20230408_Despesas.zip
[98/730] ✓ 20230406_Despesas.zip
[99/730] ✓ 20230410_Despesas.zip
[100/730] ✓ 20230411_Despesas.zip
[101/730] ✓ 20230412_Despesas.zip
[102/730] ✓ 20230415_Despesas.zip
[103/730] ✓ 20230416_Despesas.zip
[104/730] ✓ 20230413_Despesas.zip
[105/730] ✓ 20230414_Despesas.zip
[106/730] ✓ 20230417_Despesas.zip
[107/730] ✓ 20230421_Despesas.zip
[108/730] ✓ 20230418_Despesas.zip
[109/730] ✓ 20230422_Despesas.zip
[110/730] ✓ 20230423_Despesas.zip
[111/730] ✓ 20230419_Despesas.zip
[112/730] ✓ 20230420_Despesas.zip
[113/730] ✓ 20230425_Despesas.zip
[114/730] ✓ 20230424_Despesas.zip
[115/730] ✓ 20230429_Despesas.zip
[116/730] ✓ 20230430_Despesas.zip
[117/730] ✓ 20230501_Despesas.zip
[118/730] ✓ 20230426_Despesas.zip
[119/730] ✓ 20230427_Despesas.zip
[120/730] ✓ 20230428_Despesas.zip
[121/730] ✓ 20230503_Despesas.zip
[122/730] ✓ 20230502_Despesas.zip
[123/730] ✓ 20230507_Despesas.zip
[124/730] ✓ 20230506_Despesas.zip
[125/730] ✓ 20230504_Despesas.zip
[126/730] ✓ 20230505_Despesas.zip
[127/730] ✓ 20230508_Despesas.zip
[128/730] ✓ 20230510_Despesas.zip
[129/730] ✓ 20230509_Despesas.zip
[130/730] ✓ 20230513_Despesas.zip
[131/730] ✓ 20230514_Despesas.zip
[132/730] ✓ 20230511_Despesas.zip
[133/730] ✓ 20230512_Despesas.zip
[134/730] ✓ 20230516_Despesas.zip
[135/730] ✓ 20230515_Despesas.zip
[136/730] ✓ 20230517_Despesas.zip
[137/730] ✓ 20230520_Despesas.zip
[138/730] ✓ 20230521_Despesas.zip
[139/730] ✓ 20230518_Despesas.zip
[140/730] ✓ 20230519_Despesas.zip
[141/730] ✓ 20230522_Despesas.zip
[142/730] ✓ 20230524_Despesas.zip
[143/730] ✓ 20230523_Despesas.zip
[144/730] ✓ 20230527_Despesas.zip
[145/730] ✓ 20230528_Despesas.zip
[146/730] ✓ 20230526_Despesas.zip
[147/730] ✓ 20230525_Despesas.zip
[148/730] ✓ 20230529_Despesas.zip
[149/730] ✓ 20230601_Despesas.zip
[150/730] ✓ 20230603_Despesas.zip
[151/730] ✓ 20230530_Despesas.zip
[152/730] ✓ 20230604_Despesas.zip
[153/730] ✓ 20230531_Despesas.zip
[154/730] ✓ 20230602_Despesas.zip
[155/730] ✓ 20230608_Despesas.zip
[156/730] ✓ 20230609_Despesas.zip
[157/730] ✓ 20230610_Despesas.zip
[158/730] ✓ 20230611_Despesas.zip
[159/730] ✓ 20230605_Despesas.zip
[160/730] ✓ 20230607_Despesas.zip
[161/730] ✓ 20230606_Despesas.zip
[162/730] ✓ 20230612_Despesas.zip
[163/730] ✓ 20230613_Despesas.zip
[164/730] ✓ 20230617_Despesas.zip
[165/730] ✓ 20230618_Despesas.zip
[166/730] ✓ 20230614_Despesas.zip
[167/730] ✓ 20230615_Despesas.zip
[168/730] ✓ 20230616_Despesas.zip
[169/730] ✓ 20230619_Despesas.zip
[170/730] ✓ 20230621_Despesas.zip
[171/730] ✓ 20230620_Despesas.zip
[172/730] ✓ 20230624_Despesas.zip
[173/730] ✓ 20230625_Despesas.zip
[174/730] ✓ 20230622_Despesas.zip
[175/730] ✓ 20230623_Despesas.zip
[176/730] ✓ 20230627_Despesas.zip
[177/730] ✓ 20230626_Despesas.zip
[178/730] ✓ 20230628_Despesas.zip
[179/730] ✓ 20230702_Despesas.zip
[180/730] ✓ 20230701_Despesas.zip
[181/730] ✓ 20230629_Despesas.zip
[182/730] ✓ 20230703_Despesas.zip
[183/730] ✓ 20230630_Despesas.zip
[184/730] ✓ 20230704_Despesas.zip
[185/730] ✓ 20230708_Despesas.zip
[186/730] ✓ 20230709_Despesas.zip
[187/730] ✓ 20230707_Despesas.zip
[188/730] ✓ 20230706_Despesas.zip
[189/730] ✓ 20230705_Despesas.zip
[190/730] ✓ 20230710_Despesas.zip
[191/730] ✓ 20230711_Despesas.zip
[192/730] ✓ 20230715_Despesas.zip
[193/730] ✓ 20230716_Despesas.zip
[194/730] ✓ 20230712_Despesas.zip
[195/730] ✓ 20230713_Despesas.zip
[196/730] ✓ 20230714_Despesas.zip
[197/730] ✓ 20230717_Despesas.zip
[198/730] ✓ 20230718_Despesas.zip
[199/730] ✓ 20230719_Despesas.zip
[200/730] ✓ 20230722_Despesas.zip
[201/730] ✓ 20230723_Despesas.zip
[202/730] ✓ 20230720_Despesas.zip
[203/730] ✓ 20230721_Despesas.zip
[204/730] ✓ 20230724_Despesas.zip
[205/730] ✓ 20230726_Despesas.zip
[206/730] ✓ 20230725_Despesas.zip
[207/730] ✓ 20230729_Despesas.zip
[208/730] ✓ 20230730_Despesas.zip
[209/730] ✓ 20230727_Despesas.zip
[210/730] ✓ 20230728_Despesas.zip
[211/730] ✓ 20230801_Despesas.zip
[212/730] ✓ 20230731_Despesas.zip
[213/730] ✓ 20230802_Despesas.zip
[214/730] ✓ 20230805_Despesas.zip
[215/730] ✓ 20230803_Despesas.zip
[216/730] ✓ 20230806_Despesas.zip
[217/730] ✓ 20230804_Despesas.zip
[218/730] ✓ 20230807_Despesas.zip
[219/730] ✓ 20230809_Despesas.zip
[220/730] ✓ 20230812_Despesas.zip
[221/730] ✓ 20230808_Despesas.zip
[222/730] ✓ 20230813_Despesas.zip
[223/730] ✓ 20230810_Despesas.zip
[224/730] ✓ 20230811_Despesas.zip
[225/730] ✓ 20230814_Despesas.zip
[226/730] ✓ 20230815_Despesas.zip
[227/730] ✓ 20230819_Despesas.zip
[228/730] ✓ 20230820_Despesas.zip
[229/730] ✓ 20230816_Despesas.zip
[230/730] ✓ 20230818_Despesas.zip
[231/730] ✓ 20230817_Despesas.zip
[232/730] ✓ 20230821_Despesas.zip
[233/730] ✓ 20230822_Despesas.zip
[234/730] ✓ 20230826_Despesas.zip
[235/730] ✓ 20230827_Despesas.zip
[236/730] ✓ 20230823_Despesas.zip
[237/730] ✓ 20230824_Despesas.zip
[238/730] ✓ 20230825_Despesas.zip
[239/730] ✓ 20230828_Despesas.zip
[240/730] ✓ 20230829_Despesas.zip
[241/730] ✓ 20230830_Despesas.zip
[242/730] ✓ 20230902_Despesas.zip
[243/730] ✓ 20230903_Despesas.zip
[244/730] ✓ 20230901_Despesas.zip
[245/730] ✓ 20230831_Despesas.zip
[246/730] ✓ 20230904_Despesas.zip
[247/730] ✓ 20230907_Despesas.zip
[248/730] ✓ 20230905_Despesas.zip
[249/730] ✓ 20230909_Despesas.zip
[250/730] ✓ 20230910_Despesas.zip
[251/730] ✓ 20230908_Despesas.zip
[252/730] ✓ 20230906_Despesas.zip
[253/730] ✓ 20230911_Despesas.zip
[254/730] ✓ 20230912_Despesas.zip
[255/730] ✓ 20230916_Despesas.zip
[256/730] ✓ 20230917_Despesas.zip
[257/730] ✓ 20230914_Despesas.zip
[258/730] ✓ 20230913_Despesas.zip
[259/730] ✓ 20230915_Despesas.zip
[260/730] ✓ 20230918_Despesas.zip
[261/730] ✓ 20230920_Despesas.zip
[262/730] ✓ 20230919_Despesas.zip
[263/730] ✓ 20230924_Despesas.zip
[264/730] ✓ 20230923_Despesas.zip
[265/730] ✓ 20230922_Despesas.zip
[266/730] ✓ 20230921_Despesas.zip
[267/730] ✓ 20230926_Despesas.zip
[268/730] ✓ 20230925_Despesas.zip
[269/730] ✓ 20230927_Despesas.zip
[270/730] ✓ 20230930_Despesas.zip
[271/730] ✓ 20231001_Despesas.zip
[272/730] ✓ 20230928_Despesas.zip
[273/730] ✓ 20230929_Despesas.zip
[274/730] ✓ 20231003_Despesas.zip
[275/730] ✓ 20231002_Despesas.zip
[276/730] ✓ 20231007_Despesas.zip
[277/730] ✓ 20231008_Despesas.zip
[278/730] ✓ 20231004_Despesas.zip
[279/730] ✓ 20231006_Despesas.zip
[280/730] ✓ 20231005_Despesas.zip
[281/730] ✓ 20231012_Despesas.zip
[282/730] ✓ 20231009_Despesas.zip
[283/730] ✓ 20231014_Despesas.zip
[284/730] ✓ 20231013_Despesas.zip
[285/730] ✓ 20231015_Despesas.zip
[286/730] ✓ 20231010_Despesas.zip
[287/730] ✓ 20231011_Despesas.zip
[288/730] ✓ 20231017_Despesas.zip
[289/730] ✓ 20231016_Despesas.zip
[290/730] ✓ 20231021_Despesas.zip
[291/730] ✓ 20231022_Despesas.zip
[292/730] ✓ 20231018_Despesas.zip
[293/730] ✓ 20231019_Despesas.zip
[294/730] ✓ 20231020_Despesas.zip
[295/730] ✓ 20231023_Despesas.zip
[296/730] ✓ 20231024_Despesas.zip
[297/730] ✓ 20231028_Despesas.zip
[298/730] ✓ 20231029_Despesas.zip
[299/730] ✓ 20231025_Despesas.zip
[300/730] ✓ 20231026_Despesas.zip
[301/730] ✓ 20231027_Despesas.zip
[302/730] ✓ 20231030_Despesas.zip
[303/730] ✓ 20231101_Despesas.zip
[304/730] ✓ 20231102_Despesas.zip
[305/730] ✓ 20231104_Despesas.zip
[306/730] ✓ 20231105_Despesas.zip
[307/730] ✓ 20231031_Despesas.zip
[308/730] ✓ 20231103_Despesas.zip
[309/730] ✓ 20231106_Despesas.zip
[310/730] ✓ 20231107_Despesas.zip
[311/730] ✓ 20231111_Despesas.zip
[312/730] ✓ 20231112_Despesas.zip
[313/730] ✓ 20231108_Despesas.zip
[314/730] ✓ 20231109_Despesas.zip
[315/730] ✓ 20231115_Despesas.zip
[316/730] ✓ 20231110_Despesas.zip
[317/730] ✓ 20231113_Despesas.zip
[318/730] ✓ 20231118_Despesas.zip
[319/730] ✓ 20231119_Despesas.zip
[320/730] ✓ 20231114_Despesas.zip
[321/730] ✓ 20231117_Despesas.zip
[322/730] ✓ 20231116_Despesas.zip
[323/730] ✓ 20231120_Despesas.zip
[324/730] ✓ 20231121_Despesas.zip
[325/730] ✓ 20231125_Despesas.zip
[326/730] ✓ 20231126_Despesas.zip
[327/730] ✓ 20231122_Despesas.zip
[328/730] ✓ 20231123_Despesas.zip
[329/730] ✓ 20231124_Despesas.zip
[330/730] ✓ 20231127_Despesas.zip
[331/730] ✓ 20231128_Despesas.zip
[332/730] ✓ 20231129_Despesas.zip
[333/730] ✓ 20231202_Despesas.zip
[334/730] ✓ 20231130_Despesas.zip
[335/730] ✓ 20231203_Despesas.zip
[336/730] ✓ 20231204_Despesas.zip
[337/730] ✓ 20231201_Despesas.zip
[338/730] ✓ 20231205_Despesas.zip
[339/730] ✓ 20231206_Despesas.zip
[340/730] ✓ 20231210_Despesas.zip
[341/730] ✓ 20231209_Despesas.zip
[342/730] ✓ 20231208_Despesas.zip
[343/730] ✓ 20231207_Despesas.zip
[344/730] ✓ 20231213_Despesas.zip
[345/730] ✓ 20231211_Despesas.zip
[346/730] ✓ 20231215_Despesas.zip
[347/730] ✓ 20231214_Despesas.zip
[348/730] ✓ 20231216_Despesas.zip
[349/730] ✓ 20231217_Despesas.zip
[350/730] ✓ 20231218_Despesas.zip
[351/730] ✓ 20231212_Despesas.zip
[352/730] ✓ 20231219_Despesas.zip
[353/730] ✓ 20231223_Despesas.zip
[354/730] ✓ 20231220_Despesas.zip
[355/730] ✓ 20231224_Despesas.zip
[356/730] ✓ 20231225_Despesas.zip
[357/730] ✓ 20231221_Despesas.zip
[358/730] ✓ 20231222_Despesas.zip
[359/730] ✓ 20231226_Despesas.zip
[360/730] ✓ 20231227_Despesas.zip
[361/730] ✓ 20231230_Despesas.zip
[362/730] ✓ 20240101_Despesas.zip
[363/730] ✓ 20240102_Despesas.zip
[364/730] ✓ 20240103_Despesas.zip
[365/730] ✓ 20231228_Despesas.zip
[366/730] ✓ 20240104_Despesas.zip
[367/730] ✓ 20231229_Despesas.zip
[368/730] ✓ 20240105_Despesas.zip
[369/730] ✓ 20240106_Despesas.zip
[370/730] ✓ 20240107_Despesas.zip
[371/730] ✓ 20231231_Despesas.zip
[372/730] ✓ 20240110_Despesas.zip
[373/730] ✓ 20240109_Despesas.zip
[374/730] ✓ 20240108_Despesas.zip
[375/730] ✓ 20240111_Despesas.zip
[376/730] ✓ 20240114_Despesas.zip
[377/730] ✓ 20240113_Despesas.zip
[378/730] ✓ 20240112_Despesas.zip
[379/730] ✓ 20240115_Despesas.zip
[380/730] ✓ 20240117_Despesas.zip
[381/730] ✓ 20240116_Despesas.zip
[382/730] ✓ 20240121_Despesas.zip
[383/730] ✓ 20240120_Despesas.zip
[384/730] ✓ 20240118_Despesas.zip
[385/730] ✓ 20240119_Despesas.zip
[386/730] ✓ 20240122_Despesas.zip
[387/730] ✓ 20240123_Despesas.zip
[388/730] ✓ 20240127_Despesas.zip
[389/730] ✓ 20240124_Despesas.zip
[390/730] ✓ 20240128_Despesas.zip
[391/730] ✓ 20240125_Despesas.zip
[392/730] ✓ 20240126_Despesas.zip
[393/730] ✓ 20240129_Despesas.zip
[394/730] ✓ 20240130_Despesas.zip
[395/730] ✓ 20240203_Despesas.zip
[396/730] ✓ 20240131_Despesas.zip
[397/730] ✓ 20240201_Despesas.zip
[398/730] ✓ 20240202_Despesas.zip
[399/730] ✓ 20240204_Despesas.zip
[400/730] ✓ 20240205_Despesas.zip
[401/730] ✓ 20240206_Despesas.zip
[402/730] ✓ 20240207_Despesas.zip
[403/730] ✓ 20240210_Despesas.zip
[404/730] ✓ 20240211_Despesas.zip
[405/730] ✓ 20240208_Despesas.zip
[406/730] ✓ 20240209_Despesas.zip
[407/730] ✓ 20240213_Despesas.zip
[408/730] ✓ 20240212_Despesas.zip
[409/730] ✓ 20240217_Despesas.zip
[410/730] ✓ 20240218_Despesas.zip
[411/730] ✓ 20240214_Despesas.zip
[412/730] ✓ 20240216_Despesas.zip
[413/730] ✓ 20240215_Despesas.zip
[414/730] ✓ 20240219_Despesas.zip
[415/730] ✓ 20240220_Despesas.zip
[416/730] ✓ 20240221_Despesas.zip
[417/730] ✓ 20240224_Despesas.zip
[418/730] ✓ 20240222_Despesas.zip
[419/730] ✓ 20240225_Despesas.zip
[420/730] ✓ 20240223_Despesas.zip
[421/730] ✓ 20240226_Despesas.zip
[422/730] ✓ 20240227_Despesas.zip
[423/730] ✓ 20240302_Despesas.zip
[424/730] ✓ 20240228_Despesas.zip
[425/730] ✓ 20240303_Despesas.zip
[426/730] ✓ 20240229_Despesas.zip
[427/730] ✓ 20240301_Despesas.zip
[428/730] ✓ 20240304_Despesas.zip
[429/730] ✓ 20240306_Despesas.zip
[430/730] ✓ 20240305_Despesas.zip
[431/730] ✓ 20240307_Despesas.zip
[432/730] ✓ 20240309_Despesas.zip
[433/730] ✓ 20240310_Despesas.zip
[434/730] ✓ 20240308_Despesas.zip
[435/730] ✓ 20240311_Despesas.zip
[436/730] ✓ 20240312_Despesas.zip
[437/730] ✓ 20240316_Despesas.zip
[438/730] ✓ 20240313_Despesas.zip
[439/730] ✓ 20240317_Despesas.zip
[440/730] ✓ 20240314_Despesas.zip
[441/730] ✓ 20240315_Despesas.zip
[442/730] ✓ 20240319_Despesas.zip
[443/730] ✓ 20240318_Despesas.zip
[444/730] ✓ 20240323_Despesas.zip
[445/730] ✓ 20240320_Despesas.zip
[446/730] ✓ 20240324_Despesas.zip
[447/730] ✓ 20240321_Despesas.zip
[448/730] ✓ 20240322_Despesas.zip
[449/730] ✓ 20240325_Despesas.zip
[450/730] ✓ 20240326_Despesas.zip
[451/730] ✓ 20240329_Despesas.zip
[452/730] ✓ 20240330_Despesas.zip
[453/730] ✓ 20240331_Despesas.zip
[454/730] ✓ 20240327_Despesas.zip
[455/730] ✓ 20240328_Despesas.zip
[456/730] ✓ 20240401_Despesas.zip
[457/730] ✓ 20240403_Despesas.zip
[458/730] ✓ 20240402_Despesas.zip
[459/730] ✓ 20240406_Despesas.zip
[460/730] ✓ 20240407_Despesas.zip
[461/730] ✓ 20240404_Despesas.zip
[462/730] ✓ 20240405_Despesas.zip
[463/730] ✓ 20240409_Despesas.zip
[464/730] ✓ 20240408_Despesas.zip
[465/730] ✓ 20240413_Despesas.zip
[466/730] ✓ 20240410_Despesas.zip
[467/730] ✓ 20240414_Despesas.zip
[468/730] ✓ 20240411_Despesas.zip
[469/730] ✓ 20240412_Despesas.zip
[470/730] ✓ 20240415_Despesas.zip
[471/730] ✓ 20240417_Despesas.zip
[472/730] ✓ 20240416_Despesas.zip
[473/730] ✓ 20240420_Despesas.zip
[474/730] ✓ 20240421_Despesas.zip
[475/730] ✓ 20240419_Despesas.zip
[476/730] ✓ 20240418_Despesas.zip
[477/730] ✓ 20240425_Despesas.zip
[478/730] ✓ 20240424_Despesas.zip
[479/730] ✓ 20240423_Despesas.zip
[480/730] ✓ 20240428_Despesas.zip
[481/730] ✓ 20240427_Despesas.zip
[482/730] ✓ 20240422_Despesas.zip
[483/730] ✓ 20240501_Despesas.zip
[484/730] ✓ 20240426_Despesas.zip
[485/730] ✓ 20240429_Despesas.zip
[486/730] ✓ 20240504_Despesas.zip
[487/730] ✓ 20240505_Despesas.zip
[488/730] ✓ 20240503_Despesas.zip
[489/730] ✓ 20240502_Despesas.zip
[490/730] ✓ 20240430_Despesas.zip
[491/730] ✓ 20240506_Despesas.zip
[492/730] ✓ 20240507_Despesas.zip
[493/730] ✓ 20240511_Despesas.zip
[494/730] ✓ 20240508_Despesas.zip
[495/730] ✓ 20240512_Despesas.zip
[496/730] ✓ 20240509_Despesas.zip
[497/730] ✓ 20240510_Despesas.zip
[498/730] ✓ 20240513_Despesas.zip
[499/730] ✓ 20240516_Despesas.zip
[500/730] ✓ 20240514_Despesas.zip
[501/730] ✓ 20240515_Despesas.zip
[502/730] ✓ 20240519_Despesas.zip
[503/730] ✓ 20240518_Despesas.zip
[504/730] ✓ 20240517_Despesas.zip
[505/730] ✓ 20240520_Despesas.zip
[506/730] ✓ 20240522_Despesas.zip
[507/730] ✓ 20240525_Despesas.zip
[508/730] ✓ 20240526_Despesas.zip
[509/730] ✓ 20240523_Despesas.zip
[510/730] ✓ 20240521_Despesas.zip
[511/730] ✓ 20240524_Despesas.zip
[512/730] ✓ 20240530_Despesas.zip
[513/730] ✓ 20240527_Despesas.zip
[514/730] ✓ 20240601_Despesas.zip
[515/730] ✓ 20240528_Despesas.zip
[516/730] ✓ 20240602_Despesas.zip
[517/730] ✓ 20240531_Despesas.zip
[518/730] ✓ 20240529_Despesas.zip
[519/730] ✓ 20240603_Despesas.zip
[520/730] ✓ 20240604_Despesas.zip
[521/730] ✓ 20240608_Despesas.zip
[522/730] ✓ 20240605_Despesas.zip
[523/730] ✓ 20240609_Despesas.zip
[524/730] ✓ 20240607_Despesas.zip
[525/730] ✓ 20240606_Despesas.zip
[526/730] ✓ 20240610_Despesas.zip
[527/730] ✓ 20240611_Despesas.zip
[528/730] ✓ 20240615_Despesas.zip
[529/730] ✓ 20240616_Despesas.zip
[530/730] ✓ 20240612_Despesas.zip
[531/730] ✓ 20240613_Despesas.zip
[532/730] ✓ 20240614_Despesas.zip
[533/730] ✓ 20240618_Despesas.zip
[534/730] ✓ 20240619_Despesas.zip
[535/730] ✓ 20240617_Despesas.zip
[536/730] ✓ 20240622_Despesas.zip
[537/730] ✓ 20240623_Despesas.zip
[538/730] ✓ 20240620_Despesas.zip
[539/730] ✓ 20240621_Despesas.zip
[540/730] ✓ 20240625_Despesas.zip
[541/730] ✓ 20240624_Despesas.zip
[542/730] ✓ 20240629_Despesas.zip
[543/730] ✓ 20240630_Despesas.zip
[544/730] ✓ 20240627_Despesas.zip
[545/730] ✓ 20240626_Despesas.zip
[546/730] ✓ 20240628_Despesas.zip
[547/730] ✓ 20240701_Despesas.zip
[548/730] ✓ 20240702_Despesas.zip
[549/730] ✓ 20240706_Despesas.zip
[550/730] ✓ 20240703_Despesas.zip
[551/730] ✓ 20240707_Despesas.zip
[552/730] ✓ 20240705_Despesas.zip
[553/730] ✓ 20240704_Despesas.zip
[554/730] ✓ 20240708_Despesas.zip
[555/730] ✓ 20240709_Despesas.zip
[556/730] ✓ 20240713_Despesas.zip
[557/730] ✓ 20240714_Despesas.zip
[558/730] ✓ 20240710_Despesas.zip
[559/730] ✓ 20240711_Despesas.zip
[560/730] ✓ 20240712_Despesas.zip
[561/730] ✓ 20240716_Despesas.zip
[562/730] ✓ 20240715_Despesas.zip
[563/730] ✓ 20240717_Despesas.zip
[564/730] ✓ 20240720_Despesas.zip
[565/730] ✓ 20240721_Despesas.zip
[566/730] ✓ 20240718_Despesas.zip
[567/730] ✓ 20240719_Despesas.zip
[568/730] ✓ 20240723_Despesas.zip
[569/730] ✓ 20240722_Despesas.zip
[570/730] ✓ 20240727_Despesas.zip
[571/730] ✓ 20240728_Despesas.zip
[572/730] ✓ 20240724_Despesas.zip
[573/730] ✓ 20240725_Despesas.zip
[574/730] ✓ 20240726_Despesas.zip
[575/730] ✓ 20240729_Despesas.zip
[576/730] ✓ 20240730_Despesas.zip
[577/730] ✓ 20240803_Despesas.zip
[578/730] ✓ 20240801_Despesas.zip
[579/730] ✓ 20240731_Despesas.zip
[580/730] ✓ 20240804_Despesas.zip
[581/730] ✓ 20240802_Despesas.zip
[582/730] ✓ 20240805_Despesas.zip
[583/730] ✓ 20240807_Despesas.zip
[584/730] ✓ 20240806_Despesas.zip
[585/730] ✓ 20240811_Despesas.zip
[586/730] ✓ 20240810_Despesas.zip
[587/730] ✓ 20240808_Despesas.zip
[588/730] ✓ 20240809_Despesas.zip
[589/730] ✓ 20240814_Despesas.zip
[590/730] ✓ 20240812_Despesas.zip

In [17]:
pasta_anual = pasta_parquet / "anual"
pasta_anual.mkdir(exist_ok=True)

anos = ["2023", "2024"]

for ano in anos:

    arquivos_ano = sorted(
        pasta_parquet.glob(f"{ano}*_Despesas_Empenho.parquet")
    )

    print(f"\nAno {ano}")
    print(f"{len(arquivos_ano)} arquivos")

    dfs = []

    for arq in arquivos_ano:

        try:
            df = pd.read_parquet(arq)

            # equivalente ao as.character()
            df = df.astype(str)

            dfs.append(df)

        except Exception as e:
            print(arq.name, e)

    if len(dfs):

        dados_ano = pd.concat(
            dfs,
            ignore_index=True
        )

        destino = pasta_anual / f"despesas_empenho_{ano}.parquet"

        dados_ano.to_parquet(
            destino,
            index=False
        )

        print("salvo:", destino.name)

Ano 2023
364 arquivos
salvo: despesas_empenho_2023.parquet

Ano 2024
366 arquivos
salvo: despesas_empenho_2024.parquet

In [18]:
list(pasta_anual.glob("*.parquet"))

df_teste = pd.read_parquet(
    pasta_anual / "despesas_empenho_2023.parquet"
)

print(df_teste.shape)

print(df_teste.columns.tolist())

df_teste.head()

(1783391, 63)
['Id Empenho', 'Código Empenho', 'Código Empenho Resumido', 'Data Emissão', 'Código Tipo Documento', 'Tipo Documento', 'Tipo Empenho', 'Espécie Empenho', 'Código Órgão Superior', 'Órgão Superior', 'Código Órgão', 'Órgão', 'Código Unidade Gestora', 'Unidade Gestora', 'Código Gestão', 'Gestão', 'Código Favorecido', 'Favorecido', 'Observação', 'Código Esfera Orçamentária', 'Esfera Orçamentária', 'Código Tipo Crédito', 'Tipo Crédito', 'Código Grupo Fonte Recurso', 'Grupo Fonte Recurso', 'Código Fonte Recurso', 'Fonte Recurso', 'Código Unidade Orçamentária', 'Unidade Orçamentária', 'Código Função', 'Função', 'Código SubFunção', 'SubFunção', 'Código Programa', 'Programa', 'Código Ação', 'Ação', 'Linguagem Cidadã', 'Código Subtítulo (Localizador)', 'Subtítulo (Localizador)', 'Código Plano Orçamentário', 'Plano Orçamentário', 'Código Programa Governo', 'Nome Programa Governo', 'Autor Emenda', 'Código Categoria de Despesa', 'Categoria de Despesa', 'Código Grupo de Despesa', 'Grupo de Despesa', 'Código Modalidade de Aplicação', 'Modalidade de Aplicação', 'Código Elemento de Despesa', 'Elemento de Despesa', 'Processo', 'Modalidade de Licitação', 'Inciso', 'Amparo', 'Referência de Dispensa ou Inexigibilidade', 'Código Convênio', 'Contrato de Repasse / Termo de Parceria / Outros', 'Valor Original do Empenho', 'Valor do Empenho Convertido pra R$', 'Valor Utilizado na Conversão']

,Id Empenho,Código Empenho,Código Empenho Resumido,Data Emissão,Código Tipo Documento,Tipo Documento,Tipo Empenho,Espécie Empenho,Código Órgão Superior,Órgão Superior,...,Processo,Modalidade de Licitação,Inciso,Amparo,Referência de Dispensa ou Inexigibilidade,Código Convênio,Contrato de Repasse / Termo de Parceria / Outros,Valor Original do Empenho,Valor do Empenho Convertido pra R$,Valor Utilizado na Conversão
0,515902249,167233000012023NE000270,2023NE000270,01/01/2023,NE,Nota de Empenho,Global,Não se aplica,52000,Ministério da Defesa,...,64294.001707/2023-62,Dispensa de Licitação,II,LEI 8.666 / 1993,-2,-1,NAO SE APLICA,"4680,00","4680,00","1,0000"
1,526501194,250025000012022NE000123,2022NE000123,01/01/2023,NE,Nota de Empenho,Estimativo,Não se aplica,36000,Ministério da Saúde,...,25003.001658/2022-53,Pregão,SI,LEI 10.520 / 2002,-2,-1,NAO SE APLICA,"0,00","0,00","0,00"
2,561772761,167118000012023NE001715,2023NE001715,01/01/2023,NE,Nota de Empenho,Estimativo,Não se aplica,52000,Ministério da Defesa,...,64316.128466/2023-01,Inexigível,SI,LEI 8.666 / 1993,-2,-1,NAO SE APLICA,"3800,00","3800,00","1,0000"
3,515001629,152005000012023NE000045,2023NE000045,01/01/2023,NE,Nota de Empenho,Global,Não se aplica,26000,Ministério da Educação,...,23121.001232/2018-41,Pregão,SI,LEI 10.520 / 2002,-2,-1,NAO SE APLICA,"34944,00","34944,00","1,0000"
4,520401565,366003362102023NE000080,2023NE000080,02/01/2023,NE,Nota de Empenho,Ordinário,Não se aplica,36000,Ministério da Saúde,...,1328/22,Dispensa de Licitação,XV,LEI 13.303 / 2016,-2,-1,NAO SE APLICA,"1495,00","1495,00","1,0000"

In [22]:
dados_2023 = pd.read_parquet(
    pasta_anual / "despesas_empenho_2023.parquet"
)

dados_2024 = pd.read_parquet(
    pasta_anual / "despesas_empenho_2024.parquet"
)

print(dados_2023.shape)
print(dados_2024.shape)

dados_2023["Código SubFunção"] = pd.to_numeric(
    dados_2023["Código SubFunção"],
    errors="coerce"
)

dados_2024["Código SubFunção"] = pd.to_numeric(
    dados_2024["Código SubFunção"],
    errors="coerce"
)

vigilancia_2023 = dados_2023[
    dados_2023["Código SubFunção"] == 305
]

vigilancia_2024 = dados_2024[
    dados_2024["Código SubFunção"] == 305
]

print(vigilancia_2023.shape)
print(vigilancia_2024.shape)

dados_2023 = pd.read_parquet(
    pasta_anual / "despesas_empenho_2023.parquet"
)

vigilancia_2023 = dados_2023[
    pd.to_numeric(
        dados_2023["Código SubFunção"],
        errors="coerce"
    ) == 305
]

del dados_2023


dados_2024 = pd.read_parquet(
    pasta_anual / "despesas_empenho_2024.parquet"
)

vigilancia_2024 = dados_2024[
    pd.to_numeric(
        dados_2024["Código SubFunção"],
        errors="coerce"
    ) == 305
]

del dados_2024

print(vigilancia_2023.shape)
print(vigilancia_2024.shape)

(1783391, 63)
(1764026, 63)
(6491, 63)
(7409, 63)
(6491, 63)
(7409, 63)

In [23]:
dados_vigilancia = pd.concat(
    [
        vigilancia_2023,
        vigilancia_2024
    ],
    ignore_index=True
)

print(dados_vigilancia.shape)

(13900, 63)

In [24]:
dados_vigilancia["Data Emissão"] = pd.to_datetime(
    dados_vigilancia["Data Emissão"],
    dayfirst=True,
    errors="coerce"
)

dados_vigilancia["ano"] = (
    dados_vigilancia["Data Emissão"]
    .dt.year
)

dados_vigilancia["mes"] = (
    dados_vigilancia["Data Emissão"]
    .dt.month
)

dados_vigilancia["semana"] = (
    dados_vigilancia["Data Emissão"]
    .dt.isocalendar()
    .week
)

In [26]:
dados_vigilancia["Espécie Empenho"].value_counts(dropna=False)


dados_vigilancia["Valor Original do Empenho"].value_counts(dropna=False)

Valor Original do Empenho
0,00         925
100000,00     98
150000,00     80
110000,00     78
165000,00     73
            ...
69694,00       1
34992,00       1
20332,69       1
1036,00        1
34986,00       1
Name: count, Length: 8072, dtype: int64

In [27]:
dados_vigilancia.head()

,Id Empenho,Código Empenho,Código Empenho Resumido,Data Emissão,Código Tipo Documento,Tipo Documento,Tipo Empenho,Espécie Empenho,Código Órgão Superior,Órgão Superior,...,Amparo,Referência de Dispensa ou Inexigibilidade,Código Convênio,Contrato de Repasse / Termo de Parceria / Outros,Valor Original do Empenho,Valor do Empenho Convertido pra R$,Valor Utilizado na Conversão,ano,mes,semana
0,528601534,250005000012023NE000009,2023NE000009,2023-01-05,NE,Nota de Empenho,Global,Não se aplica,36000,Ministério da Saúde,...,LEI 10.520 / 2002,-2,-1,NAO SE APLICA,"33132,24","33132,24","1,0000",2023,1,1
1,509201583,250005000012023NE000010,2023NE000010,2023-01-05,NE,Nota de Empenho,Global,Não se aplica,36000,Ministério da Saúde,...,LEI 10.520 / 2002,-2,-1,NAO SE APLICA,"32916,98","32916,98","1,0000",2023,1,1
2,509401461,257001000012023NE440242,2023NE440242,2023-01-05,NE,Nota de Empenho,Global,Não se aplica,36000,Ministério da Saúde,...,SEM INFORMACAO,-2,-1,NAO SE APLICA,"35623,65","35623,65","1,0000",2023,1,1
3,523101510,257001000012023NE440243,2023NE440243,2023-01-05,NE,Nota de Empenho,Global,Não se aplica,36000,Ministério da Saúde,...,SEM INFORMACAO,-2,-1,NAO SE APLICA,"297709,58","297709,58","1,0000",2023,1,1
4,519901571,257001000012023NE440238,2023NE440238,2023-01-05,NE,Nota de Empenho,Global,Não se aplica,36000,Ministério da Saúde,...,SEM INFORMACAO,-2,-1,NAO SE APLICA,"35000,00","35000,00","1,0000",2023,1,1

In [28]:
dados_vigilancia_filtro = dados_vigilancia[
    (
        dados_vigilancia["Data Emissão"] >= "2023-10-02"
    )
    &
    (
        dados_vigilancia["Data Emissão"] <= "2024-09-27"
    )
].copy()

print(dados_vigilancia_filtro.shape)

(6743, 66)

In [29]:
dados_vigilancia_filtro["Valor Original do Empenho"] = (
    pd.to_numeric(
        dados_vigilancia_filtro["Valor Original do Empenho"]
        .astype(str)
        .str.replace(",", ".", regex=False),
        errors="coerce"
    )
)

dados_vigilancia_filtro["Valor do Empenho Convertido pra R$"] = (
    pd.to_numeric(
        dados_vigilancia_filtro["Valor do Empenho Convertido pra R$"]
        .astype(str)
        .str.replace(",", ".", regex=False),
        errors="coerce"
    )
)

In [30]:
dados_vigilancia_filtro[
    [
        "Data Emissão",
        "Valor Original do Empenho",
        "Valor do Empenho Convertido pra R$"
    ]
].head()

,Data Emissão,Valor Original do Empenho,Valor do Empenho Convertido pra R$
4275,2023-10-02,12540.00,12540.00
4276,2023-10-02,48133.05,48133.05
4277,2023-10-02,8550.00,8550.00
4278,2023-10-02,79306.16,79306.16
4279,2023-10-02,15829.58,15829.58

In [31]:
dados_vigilancia_filtro.to_csv(
    diretorio_base / "banco_diario_artigo_gustavo.csv",
    index=False,
    encoding="utf-8-sig"
)